# Generated by Django 2.0.1 on 2018-01-25 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0008_auto_20180125_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArchivo', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='static/documents')),
            ],
            options={
                'verbose_name': 'AdjuntoTrabajo',
                'verbose_name_plural': 'AdjuntoTrabajos',
            },
        ),
        migrations.CreateModel(
            name='DocumentoEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArchivo', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='static/documents')),
            ],
            options={
                'verbose_name': 'DocumentoEntrega',
                'verbose_name_plural': 'DocumentosEntrega',
            },
        ),
        migrations.CreateModel(
            name='EntregaTrabajoOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEntrega', models.DateTimeField()),
                ('comentario', models.TextField()),
                ('notaNumerica', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Alumno')),
            ],
            options={
                'verbose_name': 'EntregaTrabajoOnline',
                'verbose_name_plural': 'EntregaTrabajoOnline',
            },
        ),
        migrations.CreateModel(
            name='NotaTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notaNumerica', models.DecimalField(decimal_places=0, max_digits=2)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Alumno')),
            ],
            options={
                'verbose_name': 'NotaTrabajo',
                'verbose_name_plural': 'NotasTrabajos',
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100)),
                ('online', models.BooleanField(default=False)),
                ('fechaEntrega', models.DateTimeField()),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Asignatura')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Profesor')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
            },
        ),
        migrations.AddField(
            model_name='notatrabajo',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deberes.Trabajo'),
        ),
        migrations.AddField(
            model_name='entregatrabajoonline',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deberes.Trabajo'),
        ),
        migrations.AddField(
            model_name='documentoentrega',
            name='entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deberes.EntregaTrabajoOnline'),
        ),
        migrations.AddField(
            model_name='adjuntotrabajo',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deberes.Trabajo'),
        ),
    ]
