# Generated by Django 2.0.1 on 2018-01-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deberes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregatrabajoonline',
            old_name='notaNumerica',
            new_name='nota',
        ),
    ]
