# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0006_auto_20171208_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('documentos', models.FileField(blank=True, upload_to='static/documents')),
                ('leido', models.BooleanField(default=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Asignatura')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Profesor')),
                ('receptores', models.ManyToManyField(to='setup.Alumno')),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
            },
        ),
    ]
