# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
