# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_auto_20171208_1307'),
        ('comunicados', '0002_auto_20171208_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicado',
            name='receptores',
        ),
        migrations.AddField(
            model_name='comunicado',
            name='receptores',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='setup.Curso'),
        ),
    ]
