# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0006_auto_20171210_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunicado',
            old_name='receptor',
            new_name='receptores',
        ),
    ]
