# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_auto_20171210_1912'),
        ('comunicados', '0007_auto_20171210_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicado',
            name='leido',
        ),
        migrations.AddField(
            model_name='comunicado',
            name='alumnosLeido',
            field=models.ManyToManyField(blank=True, null=True, to='setup.Alumno'),
        ),
    ]
