# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0008_auto_20171211_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoComunicado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='static/documents')),
            ],
            options={
                'verbose_name': 'Documento Comunicado',
                'verbose_name_plural': 'Documento Comunicados',
            },
        ),
        migrations.RemoveField(
            model_name='comunicado',
            name='documentos',
        ),
        migrations.AddField(
            model_name='documentocomunicado',
            name='comunicado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='comunicados.Comunicado'),
        ),
    ]
