# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0010_auto_20171211_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentocomunicado',
            name='nombreDocumento',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
