# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0012_auto_20171211_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentocomunicado',
            name='nombreDocumento',
            field=models.CharField(default='NombreArchivo', max_length=255),
        ),
    ]
