# Generated by Django 2.0.1 on 2018-01-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0014_auto_20180125_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjuntocomunicado',
            options={'verbose_name': 'Adjunto Comunicado', 'verbose_name_plural': 'Adjuntos Comunicados'},
        ),
    ]
