# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_auto_20171013_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='token',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='profesor',
            name='token',
            field=models.CharField(default='', max_length=40),
        ),
    ]
