# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_auto_20171014_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='token',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='token',
            field=models.CharField(max_length=40),
        ),
    ]
